=== tomas-macri/1DAM_Markup/Unit 2/FINAL/public_html/xsd/provinces.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
   <xs:element name="provinces" type="typeProvinces"/>
    
    <xs:complexType name="typeProvinces">
        <xs:sequence>
            <xs:element name="province" type="typeProvince" minOccurs="24" maxOccurs="24"/>
            <xs:element name="total" type="xs:integer"/> 
            <xs:element name="quantity" type="xs:integer"/> 
            <xs:element name="beginning" type="xs:integer"/> 
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:complexType name="typeProvince">
        <xs:sequence>
            <xs:element name="full_name" type="typeFullName"/>
            <xs:element name="iso_id" type="typeISO_ID"/>
            <xs:element name="name" type="typeName"/>
            <xs:element name="id" type="typeID"/>
            <xs:element name="category" type="typeCategory"/>
            <xs:element name="populationWithPoints" type="xs:string"/>
            <xs:element name="centroid" type="typeCentroid"/>
        </xs:sequence>
        <xs:attribute name="source" fixed="IGN"/>
        <xs:attribute name="population" type="xs:integer"/>
        <xs:attribute name="alfOrder" type="xs:integer"/>
        <xs:attribute name="iso_name" type="xs:string"/>
        <xs:attribute name="capital" type="xs:string"/>
    </xs:complexType>
    
    <xs:simpleType name="typeFullName">
        <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="typeISO_ID">
        <xs:restriction base="xs:string">
            <xs:pattern value="AR-[A-Z]"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:simpleType name="typeName">
        <xs:restriction base="xs:string">
            <xs:maxLength value="80"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:simpleType name="typeID">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>   
    
    <xs:simpleType name="typeCategory">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Provincia"/>
            <xs:enumeration value="Ciudad AutÃ³noma"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="typeCentroid">
        <xs:sequence>
            <xs:element name="lat" type="typeLatLon"/>
            <xs:element name="lon" type="typeLatLon"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="typeLatLon">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="15"/>
            <xs:fractionDigits value="13"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
</xs:schema>

=== tomas-macri/1DAM_Markup/Unit 2/FINAL/public_html/xml/provinces.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!-- SOURCE JSON CODE -> https://infra.datos.gob.ar/catalog/modernizacion/dataset/7/distribution/7.2/download/provincias.json -->
<provinces
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../xsd/provinces.xsd'>
  <province source="IGN" population="1101593" alfOrder="9" iso_name="Misiones" capital="Posadas">
    <full_name>Provincia de Misiones</full_name>
    <iso_id>AR-N</iso_id>
    <name>Misiones</name>
    <id>54</id>
    <category>Provincia</category>
    <populationWithPoints>1.101.593</populationWithPoints>
    <centroid>
      <lat>-26.8753965086829</lat>
      <lon>-54.6516966230371</lon>
    </centroid>
  </province>
  <province source="IGN" population="432310" alfOrder="19" iso_name="San Luis" capital="San Luis">
    <full_name>Provincia de San Luis</full_name>
    <iso_id>AR-D</iso_id>
    <name>San Luis</name>
    <id>74</id>
    <category>Provincia</category>
    <populationWithPoints>432.310</populationWithPoints>
    <centroid>
      <lat>-33.7577257449137</lat>
      <lon>-66.0281298195836</lon>
    </centroid>
  </province>
  <province source="IGN" population="681055" alfOrder="14" iso_name="San Juan" capital="San Juan">
    <full_name>Provincia de San Juan</full_name>
    <iso_id>AR-J</iso_id>
    <name>San Juan</name>
    <id>70</id>
    <category>Provincia</category>
    <populationWithPoints>681.055</populationWithPoints>
    <centroid>
      <lat>-30.8653679979618</lat>
      <lon>-68.8894908486844</lon>
    </centroid>
  </province>
  <province source="IGN" population="1235994" alfOrder="7" iso_name="Entre Ríos" capital="Paraná">
    <full_name>Provincia de Entre Ríos</full_name>
    <iso_id>AR-E</iso_id>
    <name>Entre Ríos</name>
    <id>30</id>
    <category>Provincia</category>
    <populationWithPoints>1.235.994</populationWithPoints>
    <centroid>
      <lat>-32.0588735436448</lat>
      <lon>-59.2014475514635</lon>
    </centroid>
  </province>
  <province source="IGN" population="273964" alfOrder="23" iso_name="Santa Cruz" capital="Río Gallegos">
    <full_name>Provincia de Santa Cruz</full_name>
    <iso_id>AR-Z</iso_id>
    <name>Santa Cruz</name>
    <id>78</id>
    <category>Provincia</category>
    <populationWithPoints>273.964</populationWithPoints>
    <centroid>
      <lat>-48.8154851827063</lat>
      <lon>-69.9557621671973</lon>
    </centroid>
  </province>
  <province source="IGN" population="638645" alfOrder="15" iso_name="Río Negro" capital="Viedma">
    <full_name>Provincia de Río Negro</full_name>
    <iso_id>AR-R</iso_id>
    <name>Río Negro</name>
    <id>62</id>
    <category>Provincia</category>
    <populationWithPoints>638.645</populationWithPoints>
    <centroid>
      <lat>-40.4057957178801</lat>
      <lon>-67.229329893694</lon>
    </centroid>
  </province>
  <province source="IGN" population="509108" alfOrder="18" iso_name="Rawson">
    <full_name>Provincia del Chubut</full_name>
    <iso_id>AR-U</iso_id>
    <name>Chubut</name>
    <id>26</id>
    <category>Provincia</category>
    <populationWithPoints>509.108</populationWithPoints>
    <centroid>
      <lat>-43.7886233529878</lat>
      <lon>-68.5267593943345</lon>
    </centroid>
  </province>
  <province source="IGN" population="3308876" alfOrder="2" iso_name="Córdoba">
    <full_name>Provincia de Córdoba</full_name>
    <iso_id>AR-X</iso_id>
    <name>Córdoba</name>
    <id>14</id>
    <category>Provincia</category>
    <populationWithPoints>3.308.876</populationWithPoints>
    <centroid>
      <lat>-32.142932663607</lat>
      <lon>-63.8017532741662</lon>
    </centroid>
  </province>
  <province source="IGN" population="1738929" alfOrder="5" iso_name="Mendoza" capital="Mendoza">
    <full_name>Provincia de Mendoza</full_name>
    <iso_id>AR-M</iso_id>
    <name>Mendoza</name>
    <id>50</id>
    <category>Provincia</category>
    <populationWithPoints>1.738.929</populationWithPoints>
    <centroid>
      <lat>-34.6298873058957</lat>
      <lon>-68.5831228183798</lon>
    </centroid>
  </province>
  <province source="IGN" population="333642" alfOrder="21" iso_name="La Rioja" capital="La Rioja">
    <full_name>Provincia de La Rioja</full_name>
    <iso_id>AR-F</iso_id>
    <name>La Rioja</name>
    <id>46</id>
    <category>Provincia</category>
    <populationWithPoints>333.642</populationWithPoints>
    <centroid>
      <lat>-29.685776298315</lat>
      <lon>-67.1817359694432</lon>
    </centroid>
  </province>
  <province source="IGN" population="367828" alfOrder="20" iso_name="Catamarca" capital="San Fernando del Valle de Catamarca">
    <full_name>Provincia de Catamarca</full_name>
    <iso_id>AR-K</iso_id>
    <name>Catamarca</name>
    <id>10</id>
    <category>Provincia</category>
    <populationWithPoints>367.828</populationWithPoints>
    <centroid>
      <lat>-27.3358332810217</lat>
      <lon>-66.9476824299928</lon>
    </centroid>
  </province>
  <province source="IGN" population="318951" alfOrder="22" iso_name="La Pampa" capital="Santa Rosa">
    <full_name>Provincia de La Pampa</full_name>
    <iso_id>AR-L</iso_id>
    <name>La Pampa</name>
    <id>42</id>
    <category>Provincia</category>
    <populationWithPoints>318.951</populationWithPoints>
    <centroid>
      <lat>-37.1315537735949</lat>
      <lon>-65.4466546606951</lon>
    </centroid>
  </province>
  <province source="IGN" population="874006" alfOrder="12" iso_name="Santiago del Estero" capital="Santiago del Estero">
    <full_name>Provincia de Santiago del Estero</full_name>
    <iso_id>AR-G</iso_id>
    <name>Santiago del Estero</name>
    <id>86</id>
    <category>Provincia</category>
    <populationWithPoints>874.006</populationWithPoints>
    <centroid>
      <lat>-27.7824116550944</lat>
      <lon>-63.2523866568588</lon>
    </centroid>
  </province>
  <province source="IGN" population="992595" alfOrder="11" iso_name="Corrientes" capital="Corrientes">
    <full_name>Provincia de Corrientes</full_name>
    <iso_id>AR-W</iso_id>
    <name>Corrientes</name>
    <id>18</id>
    <category>Provincia</category>
    <populationWithPoints>992.595</populationWithPoints>
    <centroid>
      <lat>-28.7743047046407</lat>
      <lon>-57.8012191977913</lon>
    </centroid>
  </province>
  <province source="IGN" population="3194537" alfOrder="3" iso_name="Santa Fé" capital="Santa Fé">
    <full_name>Provincia de Santa Fe</full_name>
    <iso_id>AR-S</iso_id>
    <name>Santa Fe</name>
    <id>82</id>
    <category>Provincia</category>
    <populationWithPoints>3.194.537</populationWithPoints>
    <centroid>
      <lat>-30.7069271588117</lat>
      <lon>-60.9498369430241</lon>
    </centroid>
  </province>
  <province source="IGN" population="1448188" alfOrder="6" iso_name="Tucumán" capital="San Miguel de Tucumán">
    <full_name>Provincia de Tucumán</full_name>
    <iso_id>AR-T</iso_id>
    <name>Tucumán</name>
    <id>90</id>
    <category>Provincia</category>
    <populationWithPoints>1.448.188</populationWithPoints>
    <centroid>
      <lat>-26.9478001830786</lat>
      <lon>-65.3647579441481</lon>
    </centroid>
  </province>
  <province source="IGN" population="561266" alfOrder="17" iso_name="Neuquén" capital="Neuquén">
    <full_name>Provincia del Neuquén</full_name>
    <iso_id>AR-Q</iso_id>
    <name>Neuquén</name>
    <id>58</id>
    <category>Provincia</category>
    <populationWithPoints>561.266</populationWithPoints>
    <centroid>
      <lat>-38.6417575824599</lat>
      <lon>-70.1185705180601</lon>
    </centroid>
  </province>
  <province source="IGN" population="1214441" alfOrder="8" iso_name="Salta" capital="Salta">
    <full_name>Provincia de Salta</full_name>
    <iso_id>AR-A</iso_id>
    <name>Salta</name>
    <id>66</id>
    <category>Provincia</category>
    <populationWithPoints>1.214.441</populationWithPoints>
    <centroid>
      <lat>-24.2991344492002</lat>
      <lon>-64.8144629600627</lon>
    </centroid>
  </province>
  <province source="IGN" population="1055259" alfOrder="10" iso_name="Chaco" capital="Resistencia">
    <full_name>Provincia del Chaco</full_name>
    <iso_id>AR-H</iso_id>
    <name>Chaco</name>
    <id>22</id>
    <category>Provincia</category>
    <populationWithPoints>1.055.259</populationWithPoints>
    <centroid>
      <lat>-26.3864309061226</lat>
      <lon>-60.7658307438603</lon>
    </centroid>
  </province>
  <province source="IGN" population="530162" alfOrder="16" iso_name="Formosa" capital="Formosa">
    <full_name>Provincia de Formosa</full_name>
    <iso_id>AR-P</iso_id>
    <name>Formosa</name>
    <id>34</id>
    <category>Provincia</category>
    <populationWithPoints>530.162</populationWithPoints>
    <centroid>
      <lat>-24.894972594871</lat>
      <lon>-59.9324405800872</lon>
    </centroid>
  </province>
  <province source="IGN" population="673307" alfOrder="13" iso_name="Jujuy" capital="San Salvador de Jujuy">
    <full_name>Provincia de Jujuy</full_name>
    <iso_id>AR-Y</iso_id>
    <name>Jujuy</name>
    <id>38</id>
    <category>Provincia</category>
    <populationWithPoints>673.307</populationWithPoints>
    <centroid>
      <lat>-23.3200784211351</lat>
      <lon>-65.7642522180337</lon>
    </centroid>
  </province>
  <province source="IGN" population="2890151" alfOrder="4" iso_name="Ciudad Autónoma de Buenos Aires" capital="-">
    <full_name>Ciudad Autónoma de Buenos Aires</full_name>
    <iso_id>AR-C</iso_id>
    <name>Ciudad Autónoma de Buenos Aires</name>
    <id>02</id>
    <category>Ciudad Autónoma</category>
    <populationWithPoints>2.890.151</populationWithPoints>
    <centroid>
      <lat>-34.6144934119689</lat>
      <lon>-58.4458563545429</lon>
    </centroid>
  </province>
  <province source="IGN" population="15625084" alfOrder="1" iso_name="Buenos Aires" capital="La Plata">
