=== tomas-macri/1DAM_Markup/Unit 3/XMLSecondAssginment/secondXML/public_html/schemas/exercise2.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="Customer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="IDCust">
                      <xs:simpleType>
                          <xs:restriction base="xs:integer">
                              <xs:totalDigits value="5"/>
                          </xs:restriction>
                      </xs:simpleType>
                </xs:element>
                
                <xs:element name="NameCust">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                            <xs:maxLength value="8"/>
                            <xs:pattern value="([a-zA-Z])*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                
                <xs:element name="Street">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="30"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                
                <xs:element name="NumStreet">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="5000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                
                <xs:element name="PostalCode">
                    <xs:simpleType>
                          <xs:restriction base="xs:integer">
                            <xs:totalDigits value="5"/>
                          </xs:restriction>
                      </xs:simpleType>
                </xs:element>
                
                <xs:element name="City">
                    <xs:simpleType>
                          <xs:restriction base="xs:string">
                              <xs:pattern value="Madrid|Barcelona|Sevilla"/>
                          </xs:restriction>
                      </xs:simpleType>
                </xs:element>
                
                <xs:element name="Phone">
                    <xs:simpleType>
                          <xs:restriction base="xs:string">
                              <xs:pattern value="([0-9]{3}-[0-9]{3}-[0-9]{3})"/>
                          </xs:restriction>
                      </xs:simpleType>
                </xs:element>
                
                <xs:element name="DateOfBirth" type="xs:date"/>
                
                <xs:element name="Discount" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== tomas-macri/1DAM_Markup/Unit 3/XMLSecondAssginment/secondXML/public_html/xml/Exercise2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<Customer
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../schemas/exercise2.xsd'>
 <IDCust>12345</IDCust>
 <NameCust>Alicia</NameCust>
 <Street>calle del Pez </Street>
 <NumStreet>31</NumStreet>
 <PostalCode>28056</PostalCode>
 <City>Madrid</City>
 <Phone>345-567-153</Phone>
 <DateOfBirth>2001-08-14</DateOfBirth>
 <Discount>true</Discount>
</Customer>
