=== tomas-macri/1DAM_Markup/Unit 3/LastXML/finalPracticeUNITXML/public_html/xsd/articles.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="articles" type="TypeArticles"/>
    
    <xs:complexType name="TypeArticles">
        <xs:sequence>
            <xs:element name="article" type="TypeArticle" maxOccurs="unbounded"/> 
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:complexType name="TypeArticle">
        <xs:sequence>
            <xs:element name="category" type="TypeCategory"/>
            <xs:element name="detail" type="TypeDetail"/>
            <xs:element name="price" type="xs:integer"/>
            <xs:element name="order" type="TypeOrder"/>
            <xs:element name="reference" type="TypeReference"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:simpleType name="TypeCategory">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Socks"/>
            <xs:enumeration value="Sweater"/>
            <xs:enumeration value="Tshirt"/>
            <xs:enumeration value="Complements"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:simpleType name="TypeDetail">
        <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TypeOrder">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TypeReference">
        <xs:restriction base="xs:string">
            <xs:pattern value="[S,J,T,C]([0-9]){2}"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== tomas-macri/1DAM_Markup/LastXML/finalPracticeUNITXML/public_html/xml/articles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<articles
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../xsd/articles.xsd'>

    <!-- SOCKS -->
    <article>
        <category>Socks</category>
        <detail>LEOTARDS</detail>
        <price>1</price>
        <order>S</order>
        <reference>S10</reference>
    </article>
    <article>
        <category>Socks</category>
        <detail>COTTON SOCKS</detail>
        <price>2</price>
        <order>S</order>
        <reference>S37</reference>
    </article>
    <article>
        <category>Socks</category>
        <detail>SOCKS PACK</detail>
        <price>1</price>
        <order>S</order>
        <reference>S25</reference>
    </article>
    <article>
        <category>Socks</category>
        <detail>SPORT SHORT SOCKS</detail>
        <price>1</price>
        <order>S</order>
        <reference>S27</reference>
    </article>
    <article>
        <category>Socks</category>
        <detail>SPORTS LONG SOCKS</detail>
        <price>8</price>
        <order>S</order>
        <reference>S29</reference>
    </article>
    <article>
        <category>Socks</category>
        <detail>BIG SOCKS PACK</detail>
        <price>4</price>
        <order>S</order>
        <reference>S45</reference>
    </article>
    <article>
        <category>Socks</category>
        <detail>LITTLE THREAD SOCKS</detail>
        <price>15</price>
        <order>S</order>
        <reference>S06</reference>
    </article>
    <article>
        <category>Socks</category>
        <detail>LITTLE NYLON SOCKS</detail>
        <price>2</price>
        <order>S</order>
        <reference>S22</reference>
    </article>
    
    
    <!-- SWEATERS -->
    <article>
        <category>Sweater</category>
        <detail>MULTI-COLOR SWEATER</detail>
        <price>10</price>
        <order>J</order>
        <reference>J66</reference>
    </article>
    <article>
        <category>Sweater</category>
        <detail>WOOL SWEATER</detail>
        <price>15</price>
        <order>J</order>
        <reference>J14</reference>
    </article>
    <article>
        <category>Sweater</category>
        <detail>THREAD SWEATER</detail>
        <price>10</price>
        <order>J</order>
        <reference>J15</reference>
    </article>
    <article>
        <category>Sweater</category>
        <detail>COTTON SWEATER</detail>
        <price>5</price>
        <order>J</order>
        <reference>J33</reference>
    </article>
    
    
    <!-- TSHIRTS -->
    <article>
        <category>Tshirt</category>
        <detail>COTTON TSHIRTS PACK</detail>
        <price>2</price>
        <order>T</order>
        <reference>T38</reference>
    </article>
    <article>
        <category>Tshirt</category>
        <detail>NYLON TSHIRTS PACK</detail>
        <price>1</price>
        <order>T</order>
        <reference>T43</reference>
    </article>
    <article>
        <category>Tshirt</category>
        <detail>NYLON TSHIRT</detail>
        <price>2</price>
        <order>T</order>
        <reference>T36</reference>
    </article>
    <article>
        <category>Tshirt</category>
        <detail>COTTON TSHIRT</detail>
        <price>5</price>
        <order>T</order>
        <reference>T18</reference>
    </article>
    
    
    
    <!-- COMPLEMENTS -->
    <article>
        <category>Complements</category>
        <detail>WOOL SCARF</detail>
        <price>20</price>
        <order>C</order>
        <reference>C08</reference>
    </article>
    <article>
        <category>Complements</category>
        <detail>NYLON HAT</detail>
        <price>4</price>
        <order>C</order>
        <reference>C35</reference>
    </article>
    <article>
        <category>Complements</category>
        <detail>NYLON TAPE</detail>
        <price>2</price>
        <order>C</order>
        <reference>C09</reference>
    </article>
    <article>
        <category>Complements</category>
        <detail>LUXURY SILK GLOVES</detail>
        <price>3</price>
        <order>C</order>
        <reference>C80</reference>
    </article>
    <article>
        <category>Complements</category>
        <detail>SCARFS PACK</detail>
        <price>1</price>
        <order>C</order>
        <reference>C17</reference>
    </article>
    <article>
        <category>Complements</category>
        <detail>WOOL HAT</detail>
        <price>1</price>
        <order>C</order>
        <reference>C11</reference>
    </article>
    <article>
        <category>Complements</category>
        <detail>THREAD HAT</detail>
        <price>3</price>
        <order>C</order>
        <reference>C12</reference>
    </article>
    <article>
        <category>Complements</category>
        <detail>EARS COVER</detail>
        <price>3</price>
        <order>C</order>
        <reference>C13</reference>
    </article>
</articles>
